"""initial schema

Revision ID: 4f95faaf622b
Revises: 
Create Date: 2026-09-21 15:45:03.202616
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4f95faaf622b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'teacher', 'student', name='user_role', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'blocked', name='user_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role <> 'student' OR phone IS NOT NULL OR username IS NOT NULL", name=op.f('ck_users_student_requires_login_identifier')),
    sa.CheckConstraint("role <> 'teacher' OR username IS NOT NULL", name=op.f('ck_users_teacher_requires_username')),
    sa.CheckConstraint("teacher_id IS NULL OR role = 'student'", name=op.f('ck_users_only_student_has_teacher')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_users_teacher_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index('ix_users_name', 'users', ['first_name', 'last_name'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_teacher_id'), 'users', ['teacher_id'], unique=False)
    op.create_index('ix_users_teacher_role', 'users', ['teacher_id', 'role'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_fee', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='group_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('monthly_fee >= 0', name=op.f('ck_groups_monthly_fee_non_negative')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_groups_teacher_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_index(op.f('ix_groups_teacher_id'), 'groups', ['teacher_id'], unique=False)
    op.create_index('ix_groups_teacher_status', 'groups', ['teacher_id', 'status'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('jti', name=op.f('uq_refresh_tokens_jti')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_attendance_sessions_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_sessions')),
    sa.UniqueConstraint('group_id', 'session_date', name='uq_session_group_date')
    )
    op.create_index('ix_sessions_group_date', 'attendance_sessions', ['group_id', 'session_date'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('custom_fee', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='enrollment_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('joined_on', sa.Date(), nullable=False),
    sa.Column('left_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('custom_fee IS NULL OR custom_fee >= 0', name=op.f('ck_enrollments_custom_fee_non_negative')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_enrollments_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_enrollments_student_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('group_id', 'student_id', name='uq_enrollment_group_student')
    )
    op.create_index('ix_enrollments_group_status', 'enrollments', ['group_id', 'status'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'late', 'excused', name='attendance_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_attendance_records_enrollment_id_enrollments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], name=op.f('fk_attendance_records_session_id_attendance_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('session_id', 'enrollment_id', name='uq_record_session_enrollment')
    )
    op.create_index(op.f('ix_attendance_records_enrollment_id'), 'attendance_records', ['enrollment_id'], unique=False)
    op.create_table('monthly_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('amount_due', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount_due >= 0', name=op.f('ck_monthly_charges_amount_due_non_negative')),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name=op.f('ck_monthly_charges_month_range')),
    sa.CheckConstraint('year BETWEEN 2000 AND 2100', name=op.f('ck_monthly_charges_year_range')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_monthly_charges_enrollment_id_enrollments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_charges')),
    sa.UniqueConstraint('enrollment_id', 'year', 'month', name='uq_charge_enrollment_period')
    )
    op.create_index('ix_charges_period', 'monthly_charges', ['year', 'month'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('cash', 'card', 'transfer', 'other', name='payment_method', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reverses_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(reverses_id IS NULL AND amount > 0) OR (reverses_id IS NOT NULL AND amount < 0)', name=op.f('ck_payments_reversal_sign')),
    sa.CheckConstraint('amount <> 0', name=op.f('ck_payments_amount_non_zero')),
    sa.ForeignKeyConstraint(['charge_id'], ['monthly_charges.id'], name=op.f('fk_payments_charge_id_monthly_charges'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_payments_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reverses_id'], ['payments.id'], name=op.f('fk_payments_reverses_id_payments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('reverses_id', name=op.f('uq_payments_reverses_id'))
    )
    op.create_index(op.f('ix_payments_charge_id'), 'payments', ['charge_id'], unique=False)
    op.create_index('ix_payments_paid_at', 'payments', ['paid_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_paid_at', table_name='payments')
    op.drop_index(op.f('ix_payments_charge_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_charges_period', table_name='monthly_charges')
    op.drop_table('monthly_charges')
    op.drop_index(op.f('ix_attendance_records_enrollment_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index('ix_enrollments_group_status', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('ix_sessions_group_date', table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('ix_groups_teacher_status', table_name='groups')
    op.drop_index(op.f('ix_groups_teacher_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index('ix_users_teacher_role', table_name='users')
    op.drop_index(op.f('ix_users_teacher_id'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
