"""quizzes module

Testlar, bo'limlar, savollar, katalog obunasi, guruhga tayinlash, urinish
va ota-ona Telegram bog'lanishi uchun yangi jadvallar (talab: o'qituvchi
test qo'shadi/tayinlaydi, o'quvchi yechadi, natija tarixga yoziladi,
imtihon muddati tugagach ota-onaga Telegram orqali xabar boradi).

Revision ID: cab2eb1a23b3
Revises: 7c3dfbfd3ae2
Create Date: 2026-09-27
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cab2eb1a23b3"
down_revision: str | None = "7c3dfbfd3ae2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_telegram_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('link_code', sa.String(length=16), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_parent_telegram_links_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parent_telegram_links')),
    sa.UniqueConstraint('link_code', name=op.f('uq_parent_telegram_links_link_code')),
    sa.UniqueConstraint('student_id', name=op.f('uq_parent_telegram_links_student_id'))
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_catalog', sa.Boolean(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('time_limit_minutes IS NULL OR time_limit_minutes > 0', name=op.f('ck_quizzes_time_limit_positive')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_quizzes_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quizzes'))
    )
    op.create_index('ix_quizzes_catalog_subject', 'quizzes', ['is_catalog', 'subject'], unique=False)
    op.create_index(op.f('ix_quizzes_owner_id'), 'quizzes', ['owner_id'], unique=False)
    op.create_table('quiz_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('practice', 'exam', name='quiz_mode', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('score_rule', sa.Enum('best', 'average', 'latest', name='quiz_score_rule', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(mode = 'practice') OR (deadline IS NOT NULL AND max_attempts IS NOT NULL)", name=op.f('ck_quiz_assignments_exam_requires_deadline_and_limit')),
    sa.CheckConstraint('max_attempts IS NULL OR max_attempts > 0', name=op.f('ck_quiz_assignments_max_attempts_positive')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_quiz_assignments_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_assignments_quiz_id_quizzes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_quiz_assignments_teacher_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_assignments'))
    )
    op.create_index('ix_assignments_group_mode', 'quiz_assignments', ['group_id', 'mode'], unique=False)
    op.create_index(op.f('ix_quiz_assignments_group_id'), 'quiz_assignments', ['group_id'], unique=False)
    op.create_index(op.f('ix_quiz_assignments_quiz_id'), 'quiz_assignments', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_assignments_teacher_id'), 'quiz_assignments', ['teacher_id'], unique=False)
    op.create_table('quiz_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_sections_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_sections')),
    sa.UniqueConstraint('quiz_id', 'order_index', name='uq_section_order')
    )
    op.create_index(op.f('ix_quiz_sections_quiz_id'), 'quiz_sections', ['quiz_id'], unique=False)
    op.create_table('quiz_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_subscriptions_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_quiz_subscriptions_teacher_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_subscriptions')),
    sa.UniqueConstraint('teacher_id', 'quiz_id', name='uq_subscription_teacher_quiz')
    )
    op.create_index(op.f('ix_quiz_subscriptions_quiz_id'), 'quiz_subscriptions', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_subscriptions_teacher_id'), 'quiz_subscriptions', ['teacher_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'submitted', 'graded', name='quiz_attempt_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('auto_score', sa.Float(), nullable=True),
    sa.Column('manual_score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['quiz_assignments.id'], name=op.f('fk_quiz_attempts_assignment_id_quiz_assignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_quiz_attempts_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_attempts')),
    sa.UniqueConstraint('assignment_id', 'student_id', 'attempt_no', name='uq_attempt_number')
    )
    op.create_index(op.f('ix_quiz_attempts_assignment_id'), 'quiz_attempts', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_student_id'), 'quiz_attempts', ['student_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('single_choice', 'multi_choice', 'text', 'essay', name='question_type', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.JSON(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('points > 0', name=op.f('ck_quiz_questions_points_positive')),
    sa.ForeignKeyConstraint(['section_id'], ['quiz_sections.id'], name=op.f('fk_quiz_questions_section_id_quiz_sections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_questions')),
    sa.UniqueConstraint('section_id', 'order_index', name='uq_question_order')
    )
    op.create_index(op.f('ix_quiz_questions_section_id'), 'quiz_questions', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_questions_section_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_quiz_attempts_student_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_assignment_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_quiz_subscriptions_teacher_id'), table_name='quiz_subscriptions')
    op.drop_index(op.f('ix_quiz_subscriptions_quiz_id'), table_name='quiz_subscriptions')
    op.drop_table('quiz_subscriptions')
    op.drop_index(op.f('ix_quiz_sections_quiz_id'), table_name='quiz_sections')
    op.drop_table('quiz_sections')
    op.drop_index(op.f('ix_quiz_assignments_teacher_id'), table_name='quiz_assignments')
    op.drop_index(op.f('ix_quiz_assignments_quiz_id'), table_name='quiz_assignments')
    op.drop_index(op.f('ix_quiz_assignments_group_id'), table_name='quiz_assignments')
    op.drop_index('ix_assignments_group_mode', table_name='quiz_assignments')
    op.drop_table('quiz_assignments')
    op.drop_index(op.f('ix_quizzes_owner_id'), table_name='quizzes')
    op.drop_index('ix_quizzes_catalog_subject', table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_table('parent_telegram_links')
    # ### end Alembic commands ###
